### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by lccui** [CHONSPQX/modulated-deform-conv#2]
(pt) D:\detect\modulated-deform-conv> python setup.py install
running install
running bdist_egg
running egg_info
writing modulated_deform_conv.egg-info\PKG-INFO
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    cmdclass={'build_ext': BuildExtension}, zip_safe=False)
  File "C:\Users\84791\.conda\envs\pt\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\84791\.conda\envs\pt\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\84791\.conda\envs\pt\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\84791\.conda\envs\pt\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\84791\.conda\envs\pt\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\84791\.conda\envs\pt\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\84791\.conda\envs\pt\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\84791\.conda\envs\pt\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\84791\.conda\envs\pt\lib\site-packages\setuptools\command\bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "C:\Users\84791\.conda\envs\pt\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\84791\.conda\envs\pt\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\84791\.conda\envs\pt\lib\site-packages\setuptools\command\egg_info.py", line 290, in run
    writer(self, ep.name, os.path.join(self.egg_info, ep.name))
  File "C:\Users\84791\.conda\envs\pt\lib\site-packages\setuptools\command\egg_info.py", line 622, in write_pkg_info
    metadata.write_pkg_info(cmd.egg_info)
  File "C:\Users\84791\.conda\envs\pt\lib\distutils\dist.py", line 1106, in write_pkg_info
    self.write_pkg_file(pkg_info)
  File "C:\Users\84791\.conda\envs\pt\lib\site-packages\setuptools\dist.py", line 167, in write_pkg_file
    long_desc = rfc822_escape(self.get_long_description())
  File "C:\Users\84791\.conda\envs\pt\lib\distutils\util.py", line 474, in rfc822_escape
    lines = header.split('\n')
TypeError: a bytes-like object is required, not 'str'

**Comment by CHONSPQX** [comment]
the fastest way is to comment the **long_description** in setup.py
